### ISSUE TITLE
ROS2 galactic colcon build error

### ISSUE THREAD

**Issue by TZECHIN6** [autowarefoundation/lucid_vision_driver#1]
Environment:
- Docker
- ROS2 galactic
- ubuntu 20.04

Camera model: TRI032S-CC

Reproduce:
1. Install the ArenaSDK inside the Docker
2. git clone this project under workspace/src/
3. cd back to root of workpace
4. source /opt/ros/galactic/setup.bash
5. colcon build --symlink-install

Error messages:
```
Starting >>> arena_camera
--- stderr: arena_camera                             
In file included from /home/ros/lucid_camera_ws/src/lucid_vision_driver/arena_camera/src/arena_camera_node.cpp:20:
/home/ros/lucid_camera_ws/src/lucid_vision_driver/arena_camera/include/arena_camera/arena_camera_node.h:28:10: fatal error: camera_info_manager/camera_info_manager.hpp: No such file or directory
   28 | #include <camera_info_manager/camera_info_manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/arena_camera_node.dir/build.make:63: CMakeFiles/arena_camera_node.dir/src/arena_camera_node.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/arena_camera_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< arena_camera [4.42s, exited with code 2]

Summary: 0 packages finished [4.59s]
  1 package failed: arena_camera
  1 package had stderr output: arena_camera
```

On top of that question:
Inside the param file, `camera_info_url: "file:///home/zeys/projects/main_autoware/autoware/src/sensor_component/external/arena_camera/config/camera0_info.yaml"` is being called for camera param file. What is this file used for? How can I modify it to fit my camera?

**Comment by kaancolak** [comment]
Actually, this driver is not completely up-to-date but this problem looks like a dependency problem. 

`cd /YOUR/WS && rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO`


This `camera0_info.yaml` file is a camera calibration file, not mandatory to use it but if you put the path of the camera calibration file, the driver will publish the camera intrinsic as a ROS camera_info message.  

 You can calibrate your camera with ROS image_pipeline: https://github.com/ros-perception/image_pipeline/tree/humble/camera_calibration

**Comment by TZECHIN6** [comment]
Hi, first for the advice and yes, it solves the building error.

I would like to know is there a way to ignore the calibration file param when launch? I give it a empty sting "", but the console output a error about  using default calibration URL, which points to `file://home/ros/.ros/camera_info/camera_1.yaml` that I believe it also doesn't exist as well.  

I have tried comment out `camera_info_url` as well, which give an error about `rclcpp::ParameterTypeException` `expected [string] got [not set]`. I just want to test the functionality (mainly fps, as the official github repor havent implemented yet) at this stage and not care about the camera desorption.

---

Update;

Okay, I find a way to link with camera0_info.yaml in the config directory. And the camera now can be launched and image can be seen in Rviz2.

Question:

1. In the `ros2 topic hz`, the output is print as this `average rate: 0.735, min: 1.357s, max: 1.365s, std dev: 0.00223s, windows: #`
Does this mean the image topic is output in a average rate for every 0.735s, but the config set the fps as 15, so it should be much faster. What will be the problem here? I connect it with a POE switch with 100M port. 


Follow up:

I am actually also working on a autoware project too, and we purchase 6 nos of this camera model, maybe we could contribute for this public rep.

**Comment by TZECHIN6** [comment]
Update on frame rate question:

- After changing to a 1000M POE switch, the average rate boots up to 6.566 which ~ equal to 1/15. I believe it is fixed.

New Question:

- The video stream delay around 1s and buffered. Is there a way to make the stream more real-time as there is no internet transmit between host and camera. Or is this only an issue about reviewing the image in Rviz? I have GPU installed but seem the encode and decode part is not handled by GPU.

**Comment by kaancolak** [comment]
> Update on frame rate question:
> 
> * After changing to a 1000M POE switch, the average rate boots up to 6.566 which ~ equal to 1/15. I believe it is fixed.
> 
> New Question:
> 
> * The video stream delay around 1s and buffered. Is there a way to make the stream more real-time as there is no internet transmit between host and camera. Or is this only an issue about reviewing the image in Rviz? I have GPU installed but seem the encode and decode part is not handled by GPU.

This issue seems to be caused by DDS. Did you tune your DDS? 

DDS Tuning ref : [https://docs.ros.org/en/rolling/How-To-Guides/DDS-tuning.html](https://docs.ros.org/en/rolling/How-To-Guides/DDS-tuning.html)

But, If you want to communicate over nodes without consuming bandwidth so much, you need ROS2 shared memory or intra-process communication over the composable nodes.
